### ISSUE TITLE
UUID bug

### ISSUE THREAD

**Issue by enly1337** [TorchSpigot/Torch#116]
Hi. UUID does not work correct. We testing paperspigot on Pirate server and have one problem: player with any name for example: _MasterDay_ have one uuid, after leave from the server he have another uuid. Please fix it. 

![image](https://cloud.githubusercontent.com/assets/29000881/26529084/a82ae3ca-43e3-11e7-93eb-3ab1353527ff.png)

**Comment by SotrForgotten** [comment]
Does it also happen to Paper? (You mentioned paperspigot)

**Comment by enly1337** [comment]
No, its bug only on Torch spigot. We test it on paperspigot and uuid work correctly

**Comment by SotrForgotten** [comment]
Can't reproduce locally (in offline-mode), after tried joining the server and quitting several times, the uuid is still keeping consistent with the first time. I had also tried to get the uuid when the test account was offline, but nothing changed.
Note: in offline-mode, Torch generate player's UUID by its lowercase-name (instead of using the current case in vanilla or spigot), that means if you switched from Spigot(or it's another fork, Paper, etc.) and running in offline mode, the uuid will may change.

**Comment by enly1337** [comment]
Maybe have you skype for fastest communication? we will show that we (me and my few friends) have latest torch and uuid changed when player change his status.

**Comment by enly1337** [comment]
Thank you, its fixed.
